# Generated by Django 3.2.8 on 2021-11-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тренировки')),
                ('information', models.TextField(verbose_name='Информация')),
                ('difficulty', models.CharField(max_length=255, verbose_name='Сложность')),
            ],
        ),
    ]
