# Generated by Django 3.2.8 on 2021-11-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
    ]
