# Generated by Django 3.2.8 on 2021-12-01 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0002_alter_workout_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cft_complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название комплекса')),
                ('information', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Кроссфит комплекс',
                'verbose_name_plural': 'Кроссфит комплексы',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название упражнения')),
                ('information', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.RemoveField(
            model_name='workout',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='information',
        ),
        migrations.AddField(
            model_name='workout',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='Дата тренировки'),
        ),
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Crossfit_wkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(verbose_name='Количество подходов')),
                ('crf_cmplx', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainApp.cft_complex')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainApp.workout')),
            ],
            options={
                'verbose_name': 'Кроссфит тренировка',
                'verbose_name_plural': 'Кроссфит тренировки',
            },
        ),
        migrations.CreateModel(
            name='Base_wkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_number', models.IntegerField(verbose_name='Номер упражнения')),
                ('sets', models.IntegerField(verbose_name='Количество подходов')),
                ('quantity_in_set', models.IntegerField(verbose_name='Количество повторений')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainApp.exercise')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainApp.workout')),
            ],
            options={
                'verbose_name': 'Базовая тренировка',
                'verbose_name_plural': 'Базовые тренировки',
            },
        ),
    ]
