# Generated by Django 3.2.8 on 2021-12-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0003_auto_20211201_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.CharField(max_length=255, null=True, verbose_name='Email спортсмена'),
        ),
        migrations.AlterField(
            model_name='base_wkt',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainApp.exercise', verbose_name='Название упражнения'),
        ),
        migrations.AlterField(
            model_name='base_wkt',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainApp.workout', verbose_name='Название тренировки'),
        ),
        migrations.AlterField(
            model_name='crossfit_wkt',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainApp.workout', verbose_name='Название тренировки'),
        ),
    ]
