# Generated by Django 3.2.8 on 2021-12-09 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainApp', '0004_auto_20211201_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='for_all',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='Название тренировки'),
        ),
    ]
