# Generated by Django 3.2.8 on 2021-12-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0006_alter_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
    ]
