# Generated by Django 3.2.8 on 2021-12-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0009_alter_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_wkt',
            name='rest',
            field=models.IntegerField(default=0, verbose_name='Отдых между подходами (в сек)'),
            preserve_default=False,
        ),
    ]
