# Generated by Django 3.2.8 on 2021-12-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0010_base_wkt_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
