# Generated by Django 3.2.8 on 2021-12-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0011_alter_workout_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='for_all',
            field=models.BooleanField(default=1, verbose_name='Другие пользователи могут видеть эту тренировку'),
        ),
    ]
