# Generated by Django 3.2.8 on 2021-12-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0012_alter_workout_for_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название тренировки'),
        ),
    ]
