# Generated by Django 3.2.8 on 2021-12-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0013_alter_workout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_wkt',
            name='goal',
            field=models.CharField(choices=[('F', 'Сила'), ('W', 'Масса'), ('E', 'Выносливость'), ('V', 'Скорость'), ('O', 'Другое')], default=('F', 'Сила'), max_length=1),
        ),
        migrations.AddField(
            model_name='base_wkt',
            name='measurement',
            field=models.CharField(choices=[('Q', 'раз'), ('S', 'секунды')], default=('Q', 'раз'), max_length=1),
        ),
        migrations.AddField(
            model_name='crossfit_wkt',
            name='cmplx_number',
            field=models.IntegerField(default=1, verbose_name='Номер комплекса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal',
            field=models.CharField(choices=[('F', 'Сила'), ('W', 'Масса'), ('E', 'Выносливость'), ('V', 'Скорость'), ('O', 'Другое')], default=('F', 'Сила'), max_length=1),
        ),
    ]
