# Generated by Django 3.2.8 on 2021-12-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0014_auto_20211212_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_wkt',
            name='goal',
        ),
    ]
