# Generated by Django 3.2.8 on 2021-12-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0015_remove_base_wkt_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='goal',
        ),
        migrations.AlterField(
            model_name='base_wkt',
            name='measurement',
            field=models.CharField(choices=[('Q', 'раз'), ('S', 'секунды')], default=('Q', 'раз'), max_length=1, verbose_name='Мера для повторений'),
        ),
        migrations.AlterField(
            model_name='crossfit_wkt',
            name='crf_cmplx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainApp.cft_complex', verbose_name='Название комплекса'),
        ),
    ]
