# Generated by Django 3.2.8 on 2021-12-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0016_auto_20211212_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_wkt',
            name='quantity_in_set',
            field=models.IntegerField(default=12, verbose_name='Количество повторений'),
        ),
        migrations.AlterField(
            model_name='base_wkt',
            name='rest',
            field=models.IntegerField(default=60, verbose_name='Отдых между подходами (в сек)'),
        ),
        migrations.AlterField(
            model_name='base_wkt',
            name='sets',
            field=models.IntegerField(default=5, verbose_name='Количество подходов'),
        ),
        migrations.AlterField(
            model_name='crossfit_wkt',
            name='sets',
            field=models.IntegerField(default=3, verbose_name='Количество подходов'),
        ),
    ]
