# Generated by Django 3.2.8 on 2021-12-12 17:30

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0017_auto_20211212_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='cft_complex',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=''),
        ),
    ]
